# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-31 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(default='Account', max_length=32)),
                ('bookname', models.CharField(default='BookName', max_length=64)),
                ('model_pic', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/')),
                ('number', models.CharField(default='Number', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(default='Account', max_length=32)),
                ('password', models.CharField(default='Password', max_length=32)),
            ],
        ),
    ]
