# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-02 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='pub_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pub_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
