# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-03 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0002_auto_20171102_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='UserNamem', max_length=32),
        ),
    ]
