# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-02 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='pub_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='pub_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
